project:
  type: website
  render:
    - index.qmd
    - research.qmd
    - blog.qmd
    - posts/**/*.qmd

website:
  title: "Yifeng Lan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    toc: true
